### PR TITLE
Fix for build workflow

### PR DESCRIPTION
**Pull request by 3coins**
Fixes failing build workflow.

Related PRs: #24

### CODE REVIEW

**Comment by 3coins** [comment]
cc @blink1073

**Comment by fcollonval** [comment]
Hey @3coins I miss the point in #24 but this is actually not a JupyterLab frontend extension. It is a server extension with Javascript helpers. So I would:

- not add a plugin
- remove the test checking a frontend extension is installed
- remove everything related to `jupyter labextension` (like @jupyterlab/builder and the non-needed script).
- remove the `jupyterlab` entry in `package.json`

**Comment by 3coins** [comment]
@fcollonval 
You are right, we don't need the plugin here. I started with the cookiecutter extension because it provided a lot of boiler plate code, but it creates the front-end related content as well, even though I selected "server". 
I am assuming, this will need updates to the setup.py, and CI scripts as well. Is there an example project for JL3 that is similar and I can follow to make updates here?

**Comment by fcollonval** [comment]
This is quite a corner case :wink: 

The only example that comes to my mind is https://github.com/jupyterlab-contrib/jupyterlab_toastify/tree/master/packages/jupyterlab_toastify

But it does not have a server part - just a npm library. Roughly you can remove in Python and package.json everything related to building the JS assets. If you want we could set up a face-to-face. I think it will be more efficient.

**Comment by 3coins** [comment]
Thanks @fcollonval 
I feel that I need to combine what is there in jupyterlab_toastify and a pure server extension.
Face to face will be really helpful, let me know what time works for you.

**Comment by blink1073** [comment]
https://github.com/jupyter-server/jupyter_server_mathjax might be a better example.  It is a pure server extension but has some JavaScript as well.

**Comment by 3coins** [comment]
And, we have success!  
Thanks @fcollonval and @blink1073 for helping with this.

Once, this is merged how do I release the new version to conda/pypi/npm?

**Comment by blink1073** [comment]
@3coins what is your npm username?

**Comment by blink1073** [comment]
(also pypi)

**Comment by 3coins** [comment]
3coins for both.

**Comment by blink1073** [comment]
Oh, we've never published to pypi before, so you're about to claim it.  You should have an npm invite.

Next steps:
- [x] Follow the docs to make a release using [releaser](https://jupyter-releaser.readthedocs.io/en/latest/get_started/making_first_release.html)
- [x] Add `blink1073` and `zsailer` to the new pypi project.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by 3coins** [comment]
@blink1073 
I am getting this error when running the draft_changelog workflow on "jupyterlab/jupyterlab-telemetry".

```sh
COMMAND: npm version --git-tag-version false 1.0.1
125
npm ERR! Version not changed, might want --allow-same-version
```
Am I missing any permissions? I have added the "repo" and "workflow" scopes to the access token.

**Comment by 3coins** [comment]
@blink1073 
I fixed the error by specifying version spec enclosed in quotes e.g., '1.0.2', but the workflow failed in the next step.
It seems that I don't have write permissions to the repo.

```sh
COMMAND: git push origin changelog-c3a1c0ecaa3b11ec8f624db24d3f1b5b
[205](https://github.com/3coins/jupyter_releaser/runs/5652921310?check_suite_focus=true#step:4:205)
remote: Permission to jupyterlab/jupyterlab-telemetry.git denied to 3coins.
```

**Comment by blink1073** [comment]
I invited you as a collaborator on this repo

**Comment by 3coins** [comment]
@blink1073 
I am not able to run the "Full Release" workflow, might need some help figuring this one out. Here is the error I see.

```sh
Getting changes to jupyterlab/jupyterlab-telemetry since 3c1b81e3591f18326a653410f2a59bb5f6d7546d on branch master...
[154](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:154)
Running search query:
[155](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:155)
repo:jupyterlab/jupyterlab-telemetry type:pr
[156](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:156)

[157](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:157)

[158](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:158)
Found 6 items, which will take 1 pages
[159](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:159)
Found 9 items, which will take 1 pages

File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 388, in check_changelog
[176](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:176)
    changelog.check_entry(
[177](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:177)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/changelog.py", line 282, in check_entry
[178](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:178)
    raise ValueError(f"Missing PR #{pr} in changelog")
[179](https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true#step:4:179)
ValueError: Missing PR #20 in changelog
```

Workflow is complaining about PR #20, which is before the since commit sha I provided as argument. Here is the changelog compare.
https://github.com/jupyterlab/jupyterlab-telemetry/compare/3c1b81e3591f18326a653410f2a59bb5f6d7546d...15ef01e0b9c72fdb5c1d7b02638342814f20a55d

Here is the workflow run, not sure if you will be able to see the run.
https://github.com/3coins/jupyter_releaser/runs/5666843094?check_suite_focus=true

**Comment by blink1073** [comment]
I think the `since` argument is inclusive, perhaps try the one after, be69b652192d5dc25bb30a9455b3e0685f7773c8.

**Comment by 3coins** [comment]
Thanks @blink1073, that worked.

**Comment by blink1073** [comment]
Woohoo!

**Pull request merged**
